"""add_default_uuid_to_debt_id

Revision ID: 5b24c7778e06
Revises: b95afcbc3e31
Create Date: 2025-10-31 20:11:50.112705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b24c7778e06'
down_revision: Union[str, Sequence[str], None] = 'b95afcbc3e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
